project:
  type: book

execute: 
  enabled: true

lang: de
book:
  title: "Einführung in die Ökonometrie"
  author: "Boyko Amarov"
  date: "4/02/2024"
  chapters:
    - index.qmd
    - part: "Einführung in Python"
      chapters:
        - 01-Python/01-01-Basics.ipynb
        - 01-Python/01-02-Basics-Ex.ipynb
        - 01-Python/01-03-Numpy.ipynb
        - 01-Python/01-04-Pandas.ipynb
        - 01-Python/01-05-Pandas-Ex.ipynb
    - part: "Statistik Überblick"
      chapters:
        - 02-Review/01-Descriptive-Statistics.ipynb
    - part: "Das lineare Regressionsmodell"
      chapters:
        - 06-Interactions/kids.ipynb
    #     - 02-Review/02-Probability.ipynb
    # - part: "Einfache Lineare Regression"
    #   chapters:
    #     - 03-Simple-Regression/01-Continuos-Predictor.ipynb
        # - 03-Simple-Regression/02-One-Way-ANOVA.ipynb
    # - 00-Homework-Instructions.qmd
    # - 02-Statistics-Review.qmd
    # - 01-Introduction-to-R.qmd
    # - 02a-Continuous-Distributions.qmd
    # - 03-Simple-Linear-Model.qmd
    # - 04-Simple-ANOVA.qmd
    # - 05-Hypothesis-Testing-and-CI.qmd
    - Literature.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    html-math-method: katex

editor: visual
